### ISSUE TITLE
online method?

### ISSUE THREAD

**Issue by Wooho-Moon** [Ali2500/TarViS#2]
Thanks for super awesome work! I have a quick question. TarVis model can operate in online method? I just want to use this model with real time application! Can I?

**Comment by Ali2500** [comment]
In theory yes. The current code processes clips with an overlap in between e.g. 12 frame clips where the first 6 frames overlap with the previous clip. You can change this such that a new clip is processed at every frame i.e. the first 11 frames overlap with the previous clip. This way you can generate predictions each time a new frame becomes available.

This will mainly involve changing code in the [result accumulators](https://github.com/Ali2500/TarViS/tree/main/tarvis/inference/result_accumulators).

**Comment by Wooho-Moon** [comment]
Thanks for reply :) I will try ! If I need to get your advice, I may ask for your help :)
