### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by manli232111** [Ali2500/TarViS#7]
Hi 
Thanks for your excellent job! 
Did you provide visualization tool for Video Panoptic Segmentation on KITTI-STEP?

**Comment by Ali2500** [comment]
Hi, yes this should be possible by running the inference script with an additional `--viz` argument. I'm not sure if it'll look sensible for the VIPSeg dataset though because the number of classes is quite high for it.

**Comment by manli232111** [comment]
Thanks so much for your reply, I will try it
